[package]
name = "wad_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = { git = "https://github.com/nanoteck137/mime" }
